<?php
/**
 * Created by PhpStorm.
 * User: User
 * Date: 22.09.2019
 * Time: 18:22
 */

namespace Tests\Unit\Services;


use App\Services\CategoryService;
use Schema\Client;
use Schema\Collection;
use Tests\TestCase;

/**
 * @property CategoryService service
 */

class CategoryServiceTest extends TestCase
{

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->service = new CategoryService(app(Client::class));
    }

    public function test_all()
    {
        $result = $this->service->all();
        $this->assertInstanceOf(Collection::class, $result);
    }

}