<?php
/**
 * Created by PhpStorm.
 * User: User
 * Date: 22.09.2019
 * Time: 18:56
 */

namespace Tests\Unit\Services;


use App\Services\ProductService;
use Schema\Client;
use Schema\Collection;
use Tests\TestCase;

/**
 * @property ProductService service
 */
class ProductServiceTest extends TestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->service = new ProductService(app(Client::class));
    }

    public function test_all()
    {
        $result = $this->service->all();
        $this->assertInstanceOf(Collection::class, $result);
    }
}